<?xml version="1.0"?>
<stylesheet xmlns="http://www.w3.org/1999/XSL/Transform" xmlns:mei="http://www.music-encoding.org/ns/mei" version="1.0">
  <key name="id" match="*[@xml:id]" use="@xml:id"/>
  <key name="problematicIDs" match="*[@xml:id]" use="contains(@xml:id,'-_') or starts-with(@xml:id,'_')"/>
  
  <param name="checkIDsyntax" select="true()"/>
  
  <template mode="add-ids" match="/">
    <if test="$checkIDsyntax">
      <if test="key('problematicIDs',true())">
        <message terminate="yes">The source file contains IDs containing "-_". This conflicts with the ID syntax conventions used by this stylesheet
          <for-each select="key('problematicIDs',true())">
            <value-of select="@xml:id"/>
          </for-each>
        </message>
      </if>
    </if>
    <apply-templates mode="add-ids"/>
  </template>
  
  <template mode="add-ids" match="*">
    <copy>
      <apply-templates mode="write-id" select="self::*[not(@xml:id)]"/>
      <apply-templates mode="add-ids" select="@*|node()"/>
    </copy>
  </template>
  
  <template mode="add-ids" match="@*">
    <copy-of select="."/>
  </template>
  
  <template match="*[@xml:id]" mode="get-id">
    <value-of select="concat(@xml:id,'-')"/>
  </template>
  
  <template match="*" mode="get-id">
    <variable name="local-name" select="local-name()"/>
    <variable name="parentID">
      <apply-templates select="parent::*" mode="get-id"/>
    </variable>
    <value-of select="concat(           $parentID,           '_',           $local-name,           count(preceding-sibling::mei:*[local-name()=$local-name])+1         )"/>
    <!-- This test doesn't really make sense, does it?
    <if test="key('id',$ID)">
      <message terminate="yes">Autogenerated ID <value-of select="$ID"/> is in conflict with preexisting ID</message>
    </if>
    <value-of select="$ID"/> -->
  </template>
  
  <template match="*" mode="write-id">
    <attribute name="xml:id">
      <apply-templates select="." mode="get-id"/>
    </attribute>
  </template>

</stylesheet>
